/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_study_nativedemo_Hello */

#ifndef _Included_me_study_nativedemo_Hello
#define _Included_me_study_nativedemo_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_study_nativedemo_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_study_nativedemo_Hello_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
