/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_study_nativedemo_NumPlus */

#ifndef _Included_me_study_nativedemo_NumPlus
#define _Included_me_study_nativedemo_NumPlus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_study_nativedemo_NumPlus
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_me_study_nativedemo_NumPlus_getSum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
