/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_study_nativedemo_Calculate */

#ifndef _Included_me_study_nativedemo_Calculate
#define _Included_me_study_nativedemo_Calculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_study_nativedemo_Calculate
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_me_study_nativedemo_Calculate_add
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     me_study_nativedemo_Calculate
 * Method:    minus
 * Signature: (FF)F
 */
JNIEXPORT jfloat JNICALL Java_me_study_nativedemo_Calculate_minus
        (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     me_study_nativedemo_Calculate
 * Method:    multiple
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_me_study_nativedemo_Calculate_multiple
        (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     me_study_nativedemo_Calculate
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_me_study_nativedemo_Calculate_divide
        (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
