/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_study_nativedemo_Meet */

#ifndef _Included_me_study_nativedemo_Meet
#define _Included_me_study_nativedemo_Meet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_study_nativedemo_Meet
 * Method:    meeting
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_study_nativedemo_Meet_meeting
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
